language: minimal

services:
    - docker

before_install:
    - docker build -t jsks/czhttpd .

script:
    - docker run jsks/czhttpd make

after_success:
    - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
        docker push jsks/czhttpd;
      fi
